# Generated by Django 4.2.9 on 2024-01-20 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_section", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("credits", models.FloatField()),
                ("instructor", models.CharField(max_length=255)),
                ("seats_open", models.IntegerField()),
                ("status", models.CharField(max_length=255)),
                ("schedule", models.CharField(max_length=255)),
                ("room", models.CharField(max_length=255)),
                ("class_type", models.CharField(max_length=255)),
                ("delivery_method", models.CharField(max_length=255)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedules.course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="schedules.school"
            ),
        ),
    ]
