# Generated by Django 4.2.10 on 2024-04-06 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_name", models.CharField(max_length=200)),
                ("course", models.CharField(max_length=200)),
                ("course_section", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("instructor", models.CharField(max_length=200)),
                ("seats_open", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=200)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("days", models.CharField(max_length=50)),
                ("room", models.CharField(max_length=200)),
                ("class_type", models.CharField(max_length=200)),
                ("delivery_method", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("walk_time", models.IntegerField(default=0)),
                ("gap_time", models.IntegerField(default=0)),
                ("sections", models.ManyToManyField(to="schedules.section")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
