# Generated by Django 4.2.10 on 2024-04-06 08:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Schedule",
            new_name="ScheduleModel",
        ),
        migrations.RenameModel(
            old_name="Section",
            new_name="SectionModel",
        ),
    ]
