# Generated by Django 4.2.10 on 2024-04-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="seats_open",
            field=models.CharField(max_length=50),
        ),
    ]
