# Generated by Django 5.0.1 on 2024-01-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="custom_id",
            field=models.CharField(
                default=None, editable=False, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
