# Generated by Django 5.0.1 on 2024-02-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_section_custom_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="custom_id",
            new_name="section_name_id",
        ),
    ]
